### ISSUE TITLE
Token copies of permanents no longer displaying oracle text

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1044]
seen in #1040 with Captain of the Watch token.

I did post an image of this working a while ago - but can't find it anywhere. May be on the forums or as a commit comment.

**Comment by ShawnieBoy** [comment]
Looks like the issue is with Seance - Token generation first checks to see if there's any abilities before getting the oracle text. As Seance currently isn't copying the abilities, the text isn't retrieved.
(Token copy of [Myr Propogator](http://magiccards.info/som/en/182.html) on the right)

![2017-01-26_150326](https://cloud.githubusercontent.com/assets/2363180/22335994/aee6000c-e3d8-11e6-965d-14315075a1ab.png)

**Comment by lodici** [comment]
Couple of things, first the "captain of the watch" log link is incorrect, highlighting a land card on the battlefield and displaying the land card if clicked -
![screenshot00567](https://cloud.githubusercontent.com/assets/2443519/22368873/b917f9f6-e480-11e6-8e98-49dda65bb724.jpg)

Also, why can't the token card display a cropped view of the printed "captain of the watch" card? Since you have added that functionality it seems a waste not to use it here.

**Comment by ShawnieBoy** [comment]
The token card isn't displaying a cropped image because Seance isn't working correctly. That's why Myr Propagator and the Cogworker are included as they also create token copies of permanents, and they are working.

**Comment by lodici** [comment]
Do you want me to raise another issue for the link anomaly?

**Comment by ShawnieBoy** [comment]
I would expect that it would be linked to #1040  as most of the information that should be linked to the new token isn't there.
