### ISSUE TITLE
Move keywords translation out of jar.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1140]
Currently the keywords translation file is stored in the jar. Not only is this inconsistent with the way the main UI translation file is implemented, it also means the translator is unable to test changes without re-building the jar.

Suggest only storing the default English keywords file in jar and overriding it if Magarena finds a file in ``../Magarena/translations/keywords`` matching the current language setting, eg. ``../Magarena/translations/keywords/Français.txt``.

**Comment by melvinzhang** [comment]
Perhaps also move English out into the data dir, rather than treat it as a special case, to simplify the logic. Removing the need to check if it is English or not, always load from Magarena/translations/keywords/<language>.txt.

**Comment by lodici** [comment]
You need a default to fallback on. The file could be inadvertently deleted if it is outside the jar.

**Comment by melvinzhang** [comment]
I see, it always loads from data dir first even for English, no need to check language, only use built-in version if not found. Putting it in jar ensures we will also have something to show, no need to deal with error of missing default, so overall it is simpler.

**Comment by lodici** [comment]
I guess to be totally consistent you could still let Magarena override the default jar keywords file if it finds  ``Magarena/translations/keywords/English.txt.`` file. Would this be useful, I am not sure.

**Comment by melvinzhang** [comment]
Yes, it would be, for example if a translator wants to fix a bug in the English version found during translation or even to add a new keyword. It can be tested without rebuilding the jar. It is good to minimize the need to rebuild the jar to make tinkering easier.

**Comment by lodici** [comment]
Ok, I think this is a better approach. I think it is good enough to display "<file> not found" or "error reading <file>" in the keywords screen should there be a problem.

**Comment by LoubiTek** [comment]
I maybe have an idea that would simplify future translations.

Why not keep the global folder name "translations".
Then two subfolders that divide the main part / keywords.

Like this with the path, this gives for example:
- Magarena \ translations \ global \ Default and / or English.txt
- Magarena \ translations \ keywords \ Same

Thus it allows to access it easily and also to be able to modify without worrying about the jar or a recompilation.

In addition we can create two rows in the CFG general file which would indicate whether or not the translation files in question exist. With boolean values.

Example:
- globaltranslation = false
- keywordstranslation = false

If the value is false, put the file by Default so English.txt
If the value is true, set the file relative to the path to ask*

This would, in my opinion, be the most optimal and permissive way to allow a good management of future translators.
On the other hand an addition in the wiki to explain the procedure must be done!

Also, while I think about it. Another problem arises.
The one concerning these two folders/files. See above!*

I did not look at the code in detail, nor how it works.
But my proposal would be to put a pointer.

It's up to you to see how to succeed in putting all this in place.
Because I'm not an expert!
And if this is find, it is not even a problem for you.

My vision of things may not be by far the best, it is only my opinion.

Oh yes I had to talk about adding an option, like the one for global translation.
Accessible directly in the game.
This can be another way to process the problem.. :wink:
