### ISSUE TITLE
Unable to activate Cradle of the Accursed the turn it is played

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#1175]
[gameplay-report.zip](https://github.com/magarena/magarena/files/1135930/gameplay-report.zip)

This is a strange one - there is enough mana to activate the ability, but it is not highlighted - You can activate the Endless Sands and it will show that all lands have mana abilities, so it isn't that. It seems as though the Activate only as a Sorcery seems to be seeing Summoning Sickness on the land played.

**Comment by melvinzhang** [comment]
Likely a consequence of the new activation check. It is probably testing the case where you tap "Cradle of the Accursed" to pay mana, then the later tap cost is illegal so it determines that it is not possible.

This particular case can be fixed by using the "pay costs without choices first" heuristic during the activation check. Lemme get that in and see if it works.

**Comment by ShawnieBoy** [comment]
I think you're right - with further testing I'm unable to get the ability to activate regardless of turn

**Comment by melvinzhang** [comment]
@ShawnieBoy please try with the fixed order of testing. Though the current activation test is not ideal, it can rule out cases which is actually payable, for example when both costs requires some choice like in Dune Diviner, as the current version only considers taking the first option for any choice.

**Comment by ShawnieBoy** [comment]
This has fixed the situation - thanks
