### ISSUE TITLE
Luminate Primordial (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#1181]
name=Luminate Primordial
image=http://magiccards.info/scans/en/gtc/20.jpg
value=3.037
rarity=R
type=Creature
subtype=Avatar
cost={5}{W}{W}
pt=4/7
ability=Vigilance;       
timing=main
requires_groovy_code
oracle=Vigilance\nWhen Luminate Primordial enters the battlefield, for each opponent, exile up to one target creature that player controls and that player gains life equal to its power.

[
    new EntersBattlefieldTrigger() {
        @Override
        public MagicEvent executeTrigger(final MagicGame game,final MagicPermanent permanent, final MagicPayedCost payedCost) {
            return new MagicEvent(
                permanent,
                NEG_TARGET_CREATURE,
                MagicExileTargetPicker.create(),
                this,
                "Exile target creature\$. Its controller gains life equal to its power."
            );
        }
        @Override
        public void executeEvent(final MagicGame game, final MagicEvent event) {
            event.processTargetPermanent(game, {
                game.doAction(new RemoveFromPlayAction(it,MagicLocationType.Exile));
                game.doAction(new ChangeLifeAction(
                    it.getController(),
                    it.getPower()
                ));
            });
        }
    }
]

**Comment by melvinzhang** [comment]
Thanks for creating the groovy code, there are a few small bugs with it which I've fixed in the commit.
1) Exiling should be optional here as it is "up to one", so the choice needs to be MagicMayChoice
2) The creature should not be NEG_TARGET_CREATURE as that allows the player to choose his/her own creature, it should be TARGET_CREATURE_YOUR_OPPONENT_CONTROLS.
