### ISSUE TITLE
What is the point of the "Click -> to continue" prompt.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#1189]
It seems redundant.

![screenshot](https://user-images.githubusercontent.com/2443519/28229027-facf7860-68d8-11e7-8dc8-6f2df4185270.jpg)

[gameplay-report.zip](https://github.com/magarena/magarena/files/1149576/gameplay-report.zip)

**Comment by melvinzhang** [comment]
There is a pause here even though you have no instant speed action to take so that the player can observe how his/her attackers are blocked.

Without this pause, the AI would block and damage would resolve immediately and the feedback we got is that the player is confused by why this attacker died and why this attackers got this much damage etc.

The only way to figure it out previously was to go through the log to see who did damage to who and so on.

**Comment by lodici** [comment]
> There is a pause here even though you have no instant speed action to take so that the player can observe how his/her attackers are blocked.

Just to clarify, the AI is attacking, I have only basic lands in play so have nothing to block with.

**Comment by melvinzhang** [comment]
My bad, I misread the screenshot.

In this case the reason is similar, it is to allow the player to see which
creatures are attacking and anticipate how much life will be lost and
possible triggers that will occur.

Without this pause, the attackers will flick out attack, deal damage and go
back when the game auto pass. This flicking in and out of attackers is
confusing and the player needs to refer back to the log to understand what
happened.

**Comment by lodici** [comment]
Unfortunately I cannot revert back to DA from the gameplay report to be totally sure but I think the reason it stands out is that the above screen state is set in DA and then the AI thinks for 8 seconds and then it moves to DB and stops with the prompt. So I already had 8 seconds to see what is attacking then I have to press pass which just feels clunky and a needless interaction on my part.

**Comment by melvinzhang** [comment]
I see. If the AI has an instant or ability it will pause after DA to decide
if it wants to activate. If there is no instant or ability for the AI it
will declare attacker and move to DB immediately.

It would also depend on the AI level, sometimes 1s pause after DA may not
be enough to look at all the attackers if there are quite a few of them.

To keep things simple, the rule is set as 'if there are any attackers, DB
must be manually passed' so that player can consider the attackers. We can
revise and improve the rule moving forward.

**Comment by lodici** [comment]
On DA start timer. On DB if the game state has not changed (tricky but would also be useful for other stuff) or the AI did nothing (probably easier to detect) and the timer has exceeded some user-configurable threshold then auto-pass.

**Comment by melvinzhang** [comment]
The duration would also depend on the attackers, is it multiple copies of the same card attacking or five different creatures attacking. This is one of the reasons this isn't a fixed pause like waiting for stack item to resolve when you have no actions to take.
