### ISSUE TITLE
Odd land grouping behavior

### ISSUE THREAD

**Issue by tlorance** [magarena/magarena#132]
I have been playing Magarena since the very early v1 subversions, and one of the behaviors I have become quite used to is that the system automatically groups all identical lands into a block and you must choose them from the leftmost in until there is no longer any freedom of choice, at which point the system takes care of the rest.
I have noticed now (playing a monocolor deck) that the rightmost land in the group of identical lands is in a different land "block"; if you select it first, the system auto-selects the rest necessary, but if you don't, you have to select each land manually. Clearly, the system thinks that last land is of a different type, but it isn't.  I'm not sure this is even important enough to qualify as a bug; I'm mainly reporting it in case it is hiding something more serious.  I have not noticed the system miscounting the number of lands of a type, so I don't think it is interfering in that way.

**Comment by ShawnieBoy** [comment]
It's good that you've noticed, but there's a reason for it.... :smile:

If you were to use mana to animate a land, either a spell or an activated ability; as only land of different types are highlighted for selection, you can end up having mana automatically spent from your lands. In a monocolor deck that would then mean you would have to select a land that is either tapped (a bad calculation on your part :grin:), or if you have one land spare, it could be the land you played this turn, and so that animated land would then have summoning sickness and be unable to attack.

Essentially the game will prioritize lands with 'potential summoning sickness' separately from the rest.

**Comment by ShawnieBoy** [comment]
It may take a bit of getting used to, but it helps prevent the auto-generation of mana from working against you at times.

**Comment by lodici** [comment]
In simple terms then...click the right most land to auto-select all of that type?

**Comment by ShawnieBoy** [comment]
>In simple terms then...click the right most land in a block to auto-select all of that type?

If you're not trying to animate land - yup.

This would only occur if you have played a land of a type already in play.

**Comment by lodici** [comment]
Thanks, I have never really considered how the auto-select works before until tlorance brought it up but I think I will need to try it out with some examples since it obviously has hidden depths. By _animate_ do you mean something like ``Inkmoth Nexus`` which can become a "1/1 artifact..."?

**Comment by ShawnieBoy** [comment]
It can be an issue with Inkmoth Nexus. It costs 1 mana to activate, so imaging having only one in play, then playing another this turn.

You then try to activate the 'old' one, but the auto-select taps the old one for mana, so you now have a tapped, animated land.

If you try to activate the one you just played, the 'old' one would be tapped for mana, and you'd have an animated land with summoning sickness.

This way you can choose to animate the 'old' one with mana from the Nexus you've just played.

**Comment by lodici** [comment]
Phew! :cold_sweat: I think I will create a test game and step through your explanation.

**Comment by ShawnieBoy** [comment]
Another example would be with the Aura [Living Terrain](http://magiccards.info/8e/en/260.html)

You have 4 Forests already in play, and this turn you play another. You then try to cast Living Terrain on one of the land you already had in play (So that it won't have summoning sickness and you can then attack with it).

Normally the first 4 lands would be tapped for mana, making them unable to attack, and there's no point enchanting the land you just played as it would have summoning sickness.

**Comment by lodici** [comment]
Thanks I will give both examples a play.

**Comment by lodici** [comment]
Some more observations...

Given the following [saved game state (autoLandTest.game)](https://gist.github.com/lodici/3ee3fd5a27e7ab0fb3e2#file-autolandtest-game) -
![screenshot00084](https://cloud.githubusercontent.com/assets/2443519/6883373/98d246b8-d5a2-11e4-80ab-4becf001d3d7.png)
and these initial settings
![screenshot00085](https://cloud.githubusercontent.com/assets/2443519/6883384/f762964c-d5a2-11e4-9693-75d88ef59545.png)

- I play ``Master of the Feast (1BB)``. All 3 swamps are highlighted and I have to select each one because the _Automatically Pass Priority_ setting is off. I think that is confusing because I fail to see what this setting has to do with auto-land selection.
- I enable _Automatically Pass Priority_. This time it automatically selects all lands and plays the card which is great.

However, then I start a new duel using the same deck (Fireminds ``standard.Mono Black Devotion``) and get to a similar state
![screenshot00086](https://cloud.githubusercontent.com/assets/2443519/6883429/b4a08db2-d5a4-11e4-8356-794561a76f67.png)
playing the same card, _Automatically Pass Priority_ enabled, it highlights the first and last card. That looks weird and is inconsistent with the way it tapped all lands automatically above. If I select the left or right highlighted card it auto taps all. It won't let me select the middle one at all. Maybe there is method to the madness but I think it needs to be conveyed to the user in a clearer way.

**Comment by ShawnieBoy** [comment]
That's to do with the set-up of TestGames. All permanents are assumed to have entered the battlefield as the TestGame/SaveState starts (Try starting a game with untapped lands that enter the battlefield tapped).

As all the swamps in the first instance entered the battlefield at the same time, they would all be flagged as 'potential summoning sickness' and so would all be highlighted.

In the second scenario I can tell that you have played a swamp this turn (The one on the right)

**Comment by lodici** [comment]
But when I play ``Master of the Feast`` why does it not just tap all three swamps. What else could I (or it) do?

> As all the swamps in the first instance entered the battlefield at the same time, they would all be flagged as 'potential summoning sickness'

How can basic lands have 'potential summoning sickness'?

> and so would all be highlighted.
do you mean `tapped`. None are highlighted.

**Comment by ShawnieBoy** [comment]
>How can basic lands have 'potential summoning sickness'?

All non-creature permanents that enter the battlefield have 'potential summoning sickness', as if they become creatures, they haven't been under your control from the beginning of your turn, and so have summoning sickness.

>do you mean tapped? None were highlighted.

If none were highlighted, you weren't casting anything.

**Comment by lodici** [comment]
Ok, I think I am beginning to understand. The swamps are highlighed on T5 because I have just played a swamp. I waited to T6 and played ``Master of the Feast `` and it auto-tapped all cards. So my question is if there are no cards in the game that can affect the swamp just played where summoning sickness may become an issue why cannot it just auto tap as in T6?

**Comment by ShawnieBoy** [comment]
>So my question is if there are no cards in the game that can affect the swamp just played where summoning sickness may become an issue why cannot it just auto tap as in T6?

That would involve some kind of 'player AI' to look at the cards in hand as well as the permanents in play to determine if it is possible to change the type of a permanent in play.

This current mana-tapping option also allows the AI to be able to change card types more efficiently, just for the sake of having just-played lands being tapped separately.

**Comment by ShawnieBoy** [comment]
Another option would be for just played lands to have priority amongst a group of identical lands. However the mana generation in Magarena is very closely tied into the AI. This current solution was the simplest choice.

**Comment by lodici** [comment]
Ok, thanks for the explanation.

**Comment by ShawnieBoy** [comment]
Actually, I've just experienced this where I haven't played a land this turn. This was involving another land that could have been tapped for the same mana being on the battlefield, but the latest basic land was also being highlighted separately from the rest. I'm wondering if the permanent state isn't being removed at end of turn.

**Comment by ShawnieBoy** [comment]
Looking at the log, I must have the memory of a goldfish...
