### ISSUE TITLE
release "save game" for bug report feature

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#137]
lodici: The simplest case would be to remove the dev mode restriction - GameStatusPanel.getOptionsIconButton for saving and MainMenuScreen.getScreenContent() for loading. I would probably leave loading as dev mode only since it is not a fully featured save game function.

melvin: allow saving at any phase/step

lodici: If you do plan to release this for 1.60 a "Save Game State" option should be added to the game menu, not via RMB click on the options icon.

**Comment by lodici** [comment]
Shall I add a non-dev "save game" option to the game menu? Is the data currently saved suitable for debugging AI and game-play issues?

**Comment by melvinzhang** [comment]
Yes, that would be great. I have not tried to load the save data yet, at this point any kind of data saved is better than nothing.

**Comment by lodici** [comment]
Instead of "Save Game" I am planning on implementing a "Gameplay Report" option which I think from an end-user's perspective is more accurate as to its purpose. The idea is to package a game state (``snapshot.game``), ``screenshot.png`` and ``game.log`` file into a single ``gameplay-report.zip``. I have checked with the forum and it accepts the zip as an attachment. I will leave the devMode save/load options as-is since it is related more to emulating testing cases at the moment rather than a full-blown save game function.

**Comment by melvinzhang** [comment]
Great idea! The "gameplay report" is a much better name.
