### ISSUE TITLE
MCTS AI gets infinite number of choice event

### ISSUE THREAD

**Issue by Fulmene** [magarena/magarena#1406]
I'm writing groovy code for Combustible Gearhulk [here](https://github.com/Fulmene/magarena/blob/groovy-kaladesh/release/Magarena/scripts/Combustible_Gearhulk.groovy). However, when I used it against a MCTS AI, it made me draw/mill until I lost by deck out. It works just fine against a Minimax AI.

[gameplay-report.zip](https://github.com/magarena/magarena/files/1589782/gameplay-report.zip)

**Comment by melvinzhang** [comment]
Thanks for working on this script! Quick issue I see is that your action is stateful, this usually cause problems as the MagicPlayer one event, may not be the MagicPlayer object in another event, even if they refer to the same player. This is due to cloning of the game objects used by the AI.

The action should only refer to the entities it gets from the event parameter. Specifically, choiceAction should not have parameters like controller and opponent. 

Since, `it` is the player of the new event, instead of using the parameter opponent, use `event.getPlayer()` instead.

As for the controller of Gearhulk, we can pass store it in the event, just before the action. Then we can refer to it as RN in the text and `event.getRefPlayer()` in the action. Eg
```
game.addEvent(new MagicEvent(
    event.getSource(),
    it,
    new MagicMayChoice("Have Combustible Gearhulk's controller draw three cards?"),
    event.getPlayer(),
    choiceAction,
    "PN may\$ have RN draw three cards. " +
    "If PN doesn't, put the top three cards of RN's library to the graveyard, " +
    "then SN deals damage to PN equal to the total converted mana cost of those cards."
));
```

**Comment by melvinzhang** [comment]
`millAction.getMilledCards().collect({ it.getConvertedCost() }).inject(0, { result, i -> result + i });` looks a bit complicated, perhaps it can be simplified with Groovy's sum method.

**Comment by Fulmene** [comment]
Thanks for the advice. I utilised event reference and got rid of choiceAction's parameters as you said and the issue is fixed.
