### ISSUE TITLE
UCB1_C is too low.

### ISSUE THREAD

**Issue by Meerkov** [magarena/magarena#1607]
https://github.com/magarena/magarena/blob/413a5a2230de2169d1a5cc7625ef13bee7bf6e9a/src/magic/ai/MCTSAI.java#L68

Actual Code:
UCB1_C = 0.4;

Expected Code:
UCB1_C = 1.4;

Reasoning:
UCB1_C is generally assumed to be sqrt(2). Lowering the UCB1_C constant reduces exploration. So even though there may only be 2 options, one option is almost entirely unexplored, for example, in this case between
option 1) Do not block a 2/2 flyer (while at 14 hp)
option 2) Block the 2/2 flyer with a 1/1 flyer.
The computer selects option 2, because it got unlucky in the first exploration, and the exploration constant was too low for it to self correct.

e.g:
```
MCTS cheat=true index=1 life=14 turn=16 phase=DeclareBlockers sims=1099 time=8049
  [18/10/?] (S-799)
* [48/1089/?] (S-852 Majestic Heliopterus=Owl Familiar)
LOG (C): MCTS-8c blocks with <Owl Familiar~1000055>.
```

**Comment by melvinzhang** [comment]
This value was tuned empirically to find the value which gives the highest win rate over several hundred games. Though that experiment was done some time ago and the code has changed since then.

It is hard to reason on how C would affect the choice of a single action as that action has repercussions down the game tree. It will be better to compare different values of C over a series of games and look at the win rate.
