### ISSUE TITLE
MTGJSON Updates

### ISSUE THREAD

**Issue by ZeldaZach** [magarena/magarena#1637]
Hey MageArena team,

My name's Zach and I am the new maintainer of MTGJSON. I have been involved with the project since 2016, took over mid-2018 and spent the remainder of 2018 rewriting the project.

As of October 2018, I published a new release of our program titled MTGJSONv4. This release has incompatible changes with the prior releases, so I'm trying my best to reach out to every project that I find using MTGJSON to ensure they are able to handle the changes we've made.

As of now, MTGJSON is on version 4.2.2 and we'd love to help integrate support for Magarena. Let me know if there's anything you'll need!

**Comment by bilbo2** [comment]
https://github.com/magarena/magarena-scripts-builder is magarena subproject that contains the MTGJson parser for magarena.

In October 2018 I've fixed the parsing so it is able to parse MTGJSONv4.  Since then (from 4.22 to current 4.6.0+20191201) the only change is basically renaming AllSets to AllPrintings, which is now also implemented.

At the moment we can parse the newest MtgJson, so there is no help needed with that aspect, but we'll know where to ask in the future ...
