### ISSUE TITLE
Linux (Arch) Menu Help / Online Help crash

### ISSUE THREAD

**Issue by Oozenthor** [magarena/magarena#1641]
Selecting Help / Online Help from the main menu crashes the game every time.
Looks like the game does not like launching a browser under my arch Linux, dies with the error:
`The BROWSE action is not supported on the current platform!`

Can be tested for:
[https://docs.oracle.com/javase/tutorial/uiswing/misc/desktop.html](url)

might be nicer to handle the exception instead of just crashing.

there is a fix here that might work:
 [https://stackoverflow.com/questions/18004150/desktop-api-is-not-supported-on-the-current-platform](url)

Here is the [crash.log](https://github.com/magarena/magarena/files/3161693/crash.log)

Thanks

**Comment by bilbo2** [comment]
This happens also on my system ... I guess on any system with just minimalistic WM (ratpoison, openbox), without having full-blown desktop environment like gnome or KDE installed.

I have fixed all the open URL actions so that if opening the url fails, it now shows a messagebox with the URL instead of crashing.

**Comment by bilbo2** [comment]
Fixed in https://github.com/magarena/magarena/commit/f6ab9495669332b6cceea4b9ef45ff81ec1c0872
