### ISSUE TITLE
Error: Unable to access jarfile Magarena.jar

### ISSUE THREAD

**Issue by fralonra** [magarena/magarena#1642]
- os: archlinux
- openjdk: 1.8.0_212
- magarena: 1.95

I downloaded the 1.95 zip [here](https://github.com/magarena/magarena/releases), and after unzip, I ran `release/Magarena.sh`, but it gave me an error that `Error: Unable to access jarfile Magarena.jar`.
Any tips will be appreciated. Thanks a lot.

**Comment by melvinzhang** [comment]
Hi @fralonra , which zip file did you download? It sounds like you downloaded the source code of the release instead of the release it self. It should be "Magarena-1.95.zip for Linux/Windows", there is no release folder, the Magarena.sh is within a folder named Magarena-1.95. 

Alternative, you should be able to install directly from AUR. There is a packages created for Arch, see https://aur.archlinux.org/packages/magarena/

**Comment by fralonra** [comment]
@melvinzhang Thanks for your reply.
I downloaded the Magarena-1.95.zip via `Magarena-1.95.zip for Linux/Windows`, and this time everything was fine.
