### ISSUE TITLE
Magarena crashing when trying to run from command line after cloning locally

### ISSUE THREAD

**Issue by poi2000** [magarena/magarena#1643]
Hello, I was considering helping with a bit of development, and wanted to add cards from UMA, RNA, WAR, MH1 and M20 to my local version of magarena on Windows 7. I cloned magarena into my Users \...\Documents\GitHub folder and followed the instructions on the Adding New Sets wikipage to the best of my ability. When I ran magarena from windows explorer after adding set files and changing format files, nothing had changed. I then tried to run magarena from the command line using -DdevMode=true, but the program immediately crashed saying, java.lang.ExceptionInInitializerError caused by a missing file in Users\...\Magarena\decks. My hunch is that running it from the command prompt somehow told it to look for all the magarena information directly in Users\...\Magarena rather than going to Users\...\Documents\GitHub\magarena, is there a way I can fix this, or is something else going on.

**Comment by melvinzhang** [comment]
@poi2000 were you able to compile a new jar after adding the new set? Ignore devMode for now, it is unrelated to adding of new sets, it mainly turns on some extra debugging information when the game is running.

**Comment by melvinzhang** [comment]
Do include the exact command line you used to run? Including from which directory you ran the command from. It will help in troubleshooting.

**Comment by poi2000** [comment]
I tried compiling the jar using java -jar C:\Users\Byron\Documents\GitHub\magarena\release\Magarena.jar, which is where my magarena files are located. I was being told that java couldn't find the decks file for a number of directories until I tried running the command from C:\Users\Byron\Documents\GitHub, which returned the following crash report.
[crash.log](https://github.com/magarena/magarena/files/3348063/crash.log)

**Comment by melvinzhang** [comment]
`java -jar C:\Users\Byron\Documents\GitHub\magarena\release\Magarena.jar` runs the jar it doesn't compile it. Anyway to add new cards, you don't need to create the set or edit the jar. You only need to put the new card scripts in the release/Magarena/scripts folder.

I'd recommend making the release folder the current directory, then run 
`java -Xms256M -Xmx512M -noverify -jar Magarena.jar`

From the crash.log, it looks like you have file named effects.txt in  `c:\Users\Byron\Documents\GitHub\Magarena\scripts\effects.txt`  The game tries to load it as a card script and fails due to a syntax error in the script.

Generally the files in scripts should be named based on the card name, eg scripts\Zombie_Master.txt. If you attach the card script here, I can take a look at why it fails to load.
