### ISSUE TITLE
Difference between minimax [MMAB] and minimax (deck strength) [MMABFast]

### ISSUE THREAD

**Issue by jjanizek** [magarena/magarena#1656]
Hi, i'm not sure if this is really an issue, but I was trying to find some documentation on the difference between the minimax and minimax (deck strength) AIs? It seems like the latter runs a lot faster, but I was curious to find out more specific differences between the standard algorithm and the "fast" one?

Thanks!

**Comment by melvinzhang** [comment]
The AI strength is the thinking time it is allowed to use. When time is up, it does not further expand the leave nodes and immediately returns the heuristic score. It divides the allocated thinking time evenly among each branch of the search tree.

**Comment by jjanizek** [comment]
Great thank you! -- so if I'm understanding the difference correctly the standard minimax will expand for a given length of time, while the MMABFast (deck strength) only looks ahead a given number of main phases?            

looking at this line of code
`            if (DECKSTR) {
                workerGame.setMainPhases(artificialLevel);
            }`

**Comment by melvinzhang** [comment]
Ah you are asking about MMABFast, I had forgotten we label that as "minimax (deck strength)". Its name is due to the fact that it was used to provide a deck strength estimate in the Deck Editor, which has since been removed.

You are correct in that MMABFast only looks ahead a fixed number of main phases, that is how it was fast, it is also the original version of the AI you could play against. The time limit based search was added on later.

**Comment by jjanizek** [comment]
Awesome, thank you -- I've been messing around with re-implementing this paper (https://arxiv.org/pdf/1806.09771.pdf) for MTG instead of hearthstone and trying to figure out which of the Magarena AI players were fastest (and the differences between some of the different sub-versions). Thanks again!!
