### ISSUE TITLE
How well is "untap [amount] lands" used by the AI?

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#188]
@PalladiaMors any results from playtesting?

**Comment by PalladiaMors** [comment]
First thing I want to say is that if you're not feeling comfortable with those, then I'm not comfortable with them either. I absolutely trust your judgement on this.

MCTS at level 8 takes a long time to untap all the lands, period. MCTS at level 8 takes a long time to play an Island during turn 1, so I don't think this is entirely the card's fault. My opinion is, if the AI is playing a casual deck with one Palinchron or two Cloud of Faeries, this won't significantly increase the average game time. A deck full of those cards, I agree, would be annoying. I see this is a legitimate reason not to implement them, of course.

At level 8, MCTS *never* tried to untap my lands when playing one of these cards, which is good because that would rarely be good play.

At level 8, it doesn't always untap every land possible, which means it sometimes selects already untapped lands, doing the "up to" rule in practice. Looking at its hand when it didn't untap every card, I noticed that it didn't have any cards it could cast if it untapped every land it could, so it might have "seen" it as unnecessary or pointless, I don't know. If it wouldn't untap lands when it could use them, that would be a serious error. Whether or not that's happening and how frequently if it is would require further testing while looking at the AIs hand all the time. I'm willing to do that if you'd like.

As a Magic player. Historically, these cards are overpowered. This isn't the AI's fault or my fault, but WotC's fault. The reason they're overpowered, however, is how they combine with cards that generate multiple mana such as High Tide. Those cards aren't implemented, so at this point that's not a problem. If they were implemented, my opinion is that currently the AI has no chance to play reasonably well with a monster combo deck like Solidarity. In that case, they would imbalance the game in favour of the humans. As it is, without the type of cards that they combine well with, some of these are still pretty good cards like Frantic Search, some are really nothing special. Personally I don't see them as unbalancing in their current state.

The "up to" aspect. I noticed some cards with "up to" search onto hand/battlefield coded when I was trying to reach 50% in the Alliances set, which uses that mechanic a lot, and started copying them to add some other cards like Foresight, Korlash and Land Tax. This may be stupid but I swear at first I did *not* notice that those cards didn't allow you to choose less than the maximum number, I thought that the cards I had used as reference had been coded according to their text. For some reason I though you could hit the arrow button at any point to skip the remaining cards. Obviously that means that I clearly don't always playtest as carefully as I should. Only later I realized that was wrong, but then I had already added a bunch of those cards and then I though since that was already being done before, it would be fine.

I submitted the two remaining "untap up to X lands" today because I noticed you ended up not removing them and I wanted to complete the cycle. The real beast - Time Spiral - had been left out. Here's the list for reference in case you decide to take them out:

Cloud of Faeries
Frantic Search
Great Whale
Palinchron
Peregrine Drake
Rewind
Snap
Time Spiral
Treachery

Hope this nearly insane dissertation about Magic actually somehow helped, rather than leave you confused!

I won't hide that I would personally *love* to see the entire card pool - 100% of the cards, every single one - implemented. Rather than not implement something because the AI doesn't play it perfectly, I'd rather see the AI improved. I'm smart enough to understand that this might be harder to do than to just write, though.

My personal opinion about this particular subject is that whatever decision you, lodici and ShawnieBoy take is the correct decision and should be respected.

**Comment by melvinzhang** [comment]
It is not decided what do to with them at the moment, hence this issue is to have that discussion. @PalladiaMors Thanks for the playtesting and feedback on what you saw. 

My suspicious is that it will make for slow play and possibly bad plays, but this is just intuition which is highly suspect. It is good to hear that MCTS 8 didn't try to untap the opponent's lands, though I think that part is fixable with the right target hint. 

The main problem is the slow play, each untap is made separately and considered a separate choice by the AI and will take 8 seconds each. Unlike the "search for up to" which uses MagicFromCardListChoice/MagicFromCardFilterChoice that considers all the cases in one decision.

**Comment by lodici** [comment]
Sorry if this question is off topic but this discussion got me thinking. Would it be useful and more importantly, feasible, if there was some kind of advanced setting that offers a more fine grained control of the AI level. So instead of a blanket 8 seconds you could perhaps specify events/actions that would have different max thinking time from the default or vice-versa? How about an option to force the AI to cut short its thinking time and play NOW?

**Comment by melvinzhang** [comment]
@lodici Not all the algorithms are "anytime", only MCTS (and VEGAS) would be able to support this. Minimax (and MTDF) will not be able to support this as they cannot stop in the middle and be expected to give an decent response.

**Comment by melvinzhang** [comment]
Having different thinking time per choice is possible but how would it be calibrated?

**Comment by melvinzhang** [comment]
The other issue with different thing time per choice is that the AI works by evaluating options for future choices as well. It is not just what to do for the current choice, but also the choice after that and so on. So the current choice might be a simple one, but it has an impact on the choice after it. Choices are not independent, what you do at one choice has a cascading effect.

**Comment by ShawnieBoy** [comment]
>The main problem is the slow play, each untap is made separately and considered a separate choice by the AI and will take 8 seconds each. Unlike the "search for up to" which uses MagicFromCardListChoice/MagicFromCardFilterChoice that considers all the cases in one decision.

Maybe that's a possible solution - A 'permanent list' instead of a card list.

**Comment by melvinzhang** [comment]
I'm not entirely satisfied with the MagicFromCardListChoice solution, the problem there it that the number of options could be very large. Just generating all the possible options, could take several seconds and use up all the memory because the list is so large. Choosing 5 cards out of a library of 60 involves 5.4 million ways.

**Comment by ShawnieBoy** [comment]
I meant using the list format to be able to 'consider all cases in one decision' for a group of permanents. In this case Lands.

It's unlikely that 60 lands will be on the battlefield.

**Comment by melvinzhang** [comment]
Yes, I got what you are suggesting. It is feasible if the numbers are small, but I feel it is a slippery slope we are going down. The wider the list of options we allow, the weaker the AIs will perform. Instead of exploring the impact of a choice, most of the time is spent explore all the various alternatives to a single choice.

**Comment by melvinzhang** [comment]
A new type of choice that is able to select a subset of permanents from a given list of them will definitely be helpful in reducing the number of possible options here since then the order of untap is eliminated. We actually have something like this already, the attack decision is selecting a subset of possible attackers to attack. Even in this case the AI uses a custom option generation algorithm that only considers a much smaller set of options, see MagicDeclareAttackersResultBuilder

**Comment by melvinzhang** [comment]
I'm pushing back against this because I'm starting to see signs of the system breaking down with out of memory crashes when generating options. These get posted to the mailing list automatically by the continuous build system. There have been two cases this month alone.

**Comment by melvinzhang** [comment]
To use more concrete numbers, a large number of options is something above 12. 12 because that is the maximum number of blocking plans considered by the AI out of all the possibilities. The AI actually considers much more than this, but it narrows it down to the best 12 to explore further.

**Comment by ShawnieBoy** [comment]
The more I think about this, the more I think that this should be put on the back burner for a bit.

**Comment by PalladiaMors** [comment]
I want to correct one thing I said. I stated that the AI never tried to untap my lands, and even italicized the never. However, I was playtesting in "mirror" matches, using the same deck as the AI, full of the untappers. This means that I rarely had tapped lands available, so I may simply not have noticed it was picking my lands. Testing it against "normal" decks now, I see that my statement isn't true - it does untap the opponent's lands every now and then. It seems to prefer its own lands, but it does sometimes pick the opponent's. That part I believe could be fixed using pos_target_land.

Leaving this particular issue aside for the time being. I've seen some people commenting that sometimes the AI takes its full thinking time on unnecessary situations, when it doesn't have too many options available. Chess engines can do that too - if you set them for deep thinking, they'll think for a selected amount of time before choosing a move. The default setting for commercial engines, however, is to think for a few seconds, and if there's a move that leads to a much higher score than any other, stop searching and select that move. 99% of the time, that would be the selected move if it had completed its search, and this makes the engine play faster, which is more comfortable for the human player, particularly if playing blitz. If there's no clear #1 rated move, the engine keeps thinking. I don't know if maybe something like that could be attempted here, or how much work that would take.

**Comment by melvinzhang** [comment]
> The more I think about this, the more I think that this should be put on the back burner for a bit.
 
@ShawnieBoy In more actionable terms, do you mean remove these cards for the time being?

@PalladiaMors I like the suggestion, thought it would only apply to certain AIs that could stop anytime. The tricky part though is determining how much ahead the best move has to be to trigger the early termination.

**Comment by PalladiaMors** [comment]
ShawnieBoy is clearly not comfortable with this, I support moving the entire group to incomplete instead of putting it in the burner in order to avoid wasting all the work. Maybe change the target hint to pos_land in order to make sure that detail is remember if they're ever implemented waaaaay in the future.

**Comment by ShawnieBoy** [comment]
@melvinzhang I'd say maybe for the time being until the AI is more comfortable with them (Even though I'd love to be playing with Frantic Search).

@PalladiaMors 'Putting on the back burner' is a turn of phrase to have something still in mind, but put aside, not to put -in- the burner! I think it's from cooking, where the back burners are at a lower temperature for simmering.

**Comment by PalladiaMors** [comment]
Bro I know, I'm joking with you :) . You joke a lot, so I'm trying to keep up with you!

**Comment by ShawnieBoy** [comment]
doh! Sense of humour malfunction.
