### ISSUE TITLE
Empty prompt

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#200]
![empty prompt](https://cloud.githubusercontent.com/assets/2363180/7144315/ad6ca036-e2dc-11e4-9464-5379abffaa55.png)

In this image I'm trying to morph-cast - The prompt flickers for a moment with the cast/morph prompt, then goes blank.

**Comment by lodici** [comment]
Are you using...
![screenshot00113](https://cloud.githubusercontent.com/assets/2443519/7144388/157f782e-e2dd-11e4-9311-6698cdec18a4.png)

**Comment by ShawnieBoy** [comment]
I think I am - I'll let you know when I can get back in, I think this Sliver Deck just broke Magarena

**Comment by ShawnieBoy** [comment]
Yes, I am - That would explain the [Experimental] tag

**Comment by lodici** [comment]
These edge cases are what we need to know about though so we can eventually remove the "experimental" bit. Unfortunately, from the screenshot I am not clear the _exact_ preceeding steps to take to try and replicate - if you can replicate, a test case or save game would be useful.

**Comment by ShawnieBoy** [comment]
Will do - I've noticed a few edge cases, but I've not noticed a pattern as of yet. This is the first one that has prevented me from casting a spell.

**Comment by ShawnieBoy** [comment]
Just uploaded TestSliver for #192 Try making lots of Sliver tokens with the Queen - I'm getting blank prompts all the time, especially if I'm not letting each one resolve separately.

**Comment by ShawnieBoy** [comment]
How can you turn it off for TestGames - this is really annoying!

**Comment by lodici** [comment]
Assuming you have switched it off in preferences then test games should pick that up. If it is still happening then that suggests it might not necessarily be the setting causing the problem. Thanks for the test class I will give it a play.

**Comment by ShawnieBoy** [comment]
I've turned it off in preferences, but still occuring - unless it didn't save correctly

**Comment by lodici** [comment]
``hideAiActionPrompt=true`` in ``general.cfg`` if you want to check.

**Comment by ShawnieBoy** [comment]
Cool. Forgot to push the Test, should be there now >.<

**Comment by lodici** [comment]
It appears to be unrelated to ``hideAiActionPrompt``. 
- Click Queen,  it prompts for Token or Pump. I click Token.
- Click Queen, __prompt invisible__. Undo.
- Click Queen, prompt is back. Click Token.
... and it seems to work from this point onwards regardless of whether  ``hideAiActionPrompt`` is true or false.

**Comment by ShawnieBoy** [comment]
Once I undo and try again I get blank prompts still

**Comment by ShawnieBoy** [comment]
I even tried using a pump ability on the other sliver then going back to the queen, but she still was blank

**Comment by lodici** [comment]
Right then, when in doubt start switching things on and off. Switched off "Always pass priority" and that seems to have fixed it. Switch it back on and the second click, the prompt goes missing.

**Comment by ShawnieBoy** [comment]
Does turning things on and off mid-game affect things? I've tried the same and the Queen is still snubbing me.

**Comment by lodici** [comment]
Try switching off "Automatically pass priority", "Always pass during draw..." and "Allow only sensible choices" and then restart Magarena. Changing the settings in game might not necessarily affect the error and when testing it is always best to start from a clean slate.

**Comment by ShawnieBoy** [comment]
My pattern is that I can create 3 sliver tokens, after that she refuses - I'll restart this game and see.

**Comment by lodici** [comment]
Nah, that doesn't work either - it fell over after five. This is starting to look suspiciously like a threading issue.

**Comment by ShawnieBoy** [comment]
2 for me

**Comment by lodici** [comment]
Went back to 3f5d8419854 (1.60 tag) and it all works fine regardless of the ``hideAiActionPrompt`` setting (or any other setting for that matter).

**Comment by ShawnieBoy** [comment]
Damn

**Comment by lodici** [comment]
@melvinzhang this issue seems to be caused by 6cc4825510da2. Not sure exactly why yet, I just narrowed it down by divide and conquer. My bet is on the changes to ``MagicMessage``. Basically, when I reset to this commit it always produces the steps shown [above](https://github.com/magarena/magarena/issues/200#issuecomment-93124521).

**Comment by melvinzhang** [comment]
@lodici Thanks for nailing this down. Agree, I'm able to replicate at 6cc4825 but not before.

**Comment by lodici** [comment]
And just to confirm it is the changes to ``MagicMessage`` that are causing it.

**Comment by melvinzhang** [comment]
I wasn't getting anywhere trying to look into MagicMessage as what it does is alter a display string and not related to repainting/updating the UI. However, a change that is related is the update to the clearValidChoices to also clear the message. The problem is clearValidChoices call clearDisplayedValidChoices which contains a call to showMessage to clear the action panel message. However this call is via invokeLater. 

It was possible that the order of the invokeLater calls is interleaved as follows
1) clearChoices
2) update action panel with the [Token] [Pump] menu
3) showMessage with empty string (which will remove the action panel with [Token] [Pump])

This is because the showMessage is not run directly but rather by an invoke later call. Although 1) is enqueued before 2), 1) may not execute on the EDT before 2) is enqueued. When this occurs, 3) will enqueue after 2) and result in the empty prompt.

The fix is to enqueue 1) and 3) at the same time, rather than rely on the execution of 1) to enqueue 3). Implemented in the above commit.

**Comment by melvinzhang** [comment]
Please help to test the fix. Leaving this as open for now to await more confirmation that the bug is really addressed.

**Comment by lodici** [comment]
Nice solution to a very subtle multi-thread gotcha. I tested with TestSlivers and it seems to be behaving itself. @ShawnieBoy please can you confirm everything is working for you as well.

**Comment by ShawnieBoy** [comment]
All working good here with the TestSlivers now - can really see the CPU getting thrashed too :+1:
