### ISSUE TITLE
Damage prevention with damage replacement

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#229]
While putting together [Crumbling Sanctuary](http://magiccards.info/mm/en/292.html) and [Palisade Giant](http://magiccards.info/rtr/en/15.html), I've stumbled across a possible issue. (Ignoring the fact that you can't choose which replacement effect to apply).

As damage replacement is dealing with damage before it is dealt, it's unable to take into account any damage prevention, as that is determined from damage dealt.

I'll push a TestCrumbling to better display the effects.

**Comment by melvinzhang** [comment]
I think the issue here is that damage replacement due to one shot effects (prevent the next [n] damage that would be dealt to target permanent this turn) is not handled at the same level as continuous effects (If a source would deal damage to you, prevent 1 of that damage). The former is applied after IfDamageWouldBeDealt effects, the later is part of IfDamageWouldBeDealt (at the prevent damage level).

If we move the former to some kind of global IfDamageWouldBeDealt that checks if a permanent has prevent damage shield, I think it should resolve the discrepancy.

**Comment by melvinzhang** [comment]
pushed the suggested fix in b72f7010a40

Samite Healer self + Lightning Helix self moves only two cards to exile instead of three.
