### ISSUE TITLE
Remember last window size

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#230]
Is there a way for Magarena to remember it's last window size when launching? I'm rescaling it (I don't always want it full screen), every time it launches. Would be a handy feature (for me!).

**Comment by lodici** [comment]
Should now remember window position and size on restart. Will also restore to maximized state (not the same as full screen). This will be useful on the Mac since in my experience full screen does not work - for some reason F11 "rolls" the window up into the top of the screen! To reset to default (min size, center of screen) close Magarena with the window overlapping the screen edge.
