### ISSUE TITLE
casting a card without paying its mana cost does not require paying additional costs

### ISSUE THREAD

**Issue by tlorance** [magarena/magarena#231]
I activated Isochron Sceptre (having exiled Shrapnel Blast) and it did not require that I exile an artifact to activate.  According to gatherer.wizards.com, **_If you cast a card "without paying its mana cost," you can't pay any alternative costs. You can pay additional costs such as kicker costs. If the card has mandatory additional costs, you must pay those.**_
I can see how this might be difficult to implement, since elsewhere it says you aren't allowed to pay any of the cost if you cannot pay it all (although I'm not sure how that works with a two-stage play process like the Sceptre effect); that would require checking the additional costs of the exiled card before allowing the player to pay two and tap the Sceptre (but, as alluded to above, perhaps it doesn't work that way).

**Comment by ShawnieBoy** [comment]
Looks like CastFreeCopyAction should add back in any additional casting costs.
Or MagicPayedCost.No_Cost should return them.

**Comment by ShawnieBoy** [comment]
I've had a look at this but can't work out where to make any edits - any ideas @melvinzhang?

**Comment by melvinzhang** [comment]
@ShawnieBoy Isochron_Scepter.groovy getCostEvent should include the additional costs of the card.

**Comment by melvinzhang** [comment]
Alternatively check that additional costs are payable in executeEvent and then pay them there, else do nothing. Similar to the "[effect] unless [cost]", eg Junk_Golem.groovy.

**Comment by ShawnieBoy** [comment]
This more than just an Isochron Scepter issue - It's a whole 'Cast <card> without paying it's mana cost' issue when involving spells with compulsory additional costs. It's either replacing them or ignoring them. That's why I've been looking at the `CastFreeCopyAction` and `MagicPayedCost.No_Cost`

We shouldn't be doing checks for each card that enables 'free' spells, it should be functioning in-engine.

I've pushed a TestFreeSpells to better show.

**Comment by melvinzhang** [comment]
It depends on how you want it to work, the modifications for getCostEvent
will only work for activated use of this effect but it has the nice
property that if you can't pay the additional cost you can't activate the
ability. It doesn't seem possible to do this in a non card specific way.
Since the is combining the additional cost into the activation cost.

The modification of executeEvent can be integrated into CastFreeCopy. The
cons is you can activate the ability and it will go on the stack but fail
when it resolves and you can't pay the additional cost.

**Comment by melvinzhang** [comment]
The second method is generic, basically anything done in executeEvent can
always be wrapped up in an event or action and reused elsewhere. I think it
is the most appropriate but the player needs some notification that paying
of additional costs failed.

**Comment by ShawnieBoy** [comment]
I think playing the effect and the notifying of failure would be the best way to go, as there will be times when something happens to make a casting become illegal.

**Comment by ShawnieBoy** [comment]
The only possible problem may be getting it mixed in with copies that get put onto the stack instead of being cast, but I don't think they will clash.

**Comment by melvinzhang** [comment]
Cards not using CastFreeAction and still having issues:
release/Magarena/scripts/Leaf_Crowned_Elder.groovy
release/Magarena/scripts/Maelstrom_Archangel.groovy
release/Magarena/scripts/Snapcaster_Mage.groovy
release/Magarena/scripts/Wrexial__the_Risen_Deep.groovy

**Comment by melvinzhang** [comment]
CastCardAction.WithoutManaCost correctly requires additional costs to be paid.
