### ISSUE TITLE
Phantasmal Sphere breaks AI

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#304]
df90c5ee95887eb10f2f3b614e4cdc9cae4cd219
Pushed the above, including a test scenario which has the player with a sphere in play, and the AI with one in hand.

I'm fairly sure the mechanics of the Sphere are ok, although I have some concern about the TARGET_OPPONENT.

Either way this will seem to get into a thinking loop (?) with the test, or in-game, crash with no log.

**Comment by melvinzhang** [comment]
The bug is using WhenLeavesPlay instead of WhenSelfLeavesPlay. The problem with WhenLeavesPlay is due to it also catching the tokens leaving play. Phantasmal Sphere with 0 +1/+1 tokens die in combat, puts 0/0 token into play, token dies due to being 0/0 triggers WhenLeavesPlay, put 0/0 token into play, ...

**Comment by melvinzhang** [comment]
fixed in https://github.com/magarena/magarena/commit/467fa44c3aedd1660d7a1bac950cd9eebcfd973d

**Comment by ShawnieBoy** [comment]
Ahh, of course! I completely missed checking the trigger type.

Thanks for that
