### ISSUE TITLE
opening deck editor when setting up a duel, should have the selected cube filter enabled

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#373]

**Comment by lodici** [comment]
See also issue #311. I don't think it is enough just to select the appropriate cube filter since it could easily be changed. The cube is currently set for the whole duel during the duel setup screen but then can be changed via the deck editor - poor design. Then the cube only applies when generating random color decks, but you can open the deck editor and select any prebuilt deck regardless of the cube setting. How a duel is configured in terms of the pool of cards available needs to be looked at first, imo.

**Comment by melvinzhang** [comment]
Thanks for the reminder about #311, it slipped off my radar. We should make a decision about it and decide a course of action. I've summarized my proposal in a new comment on #311

**Comment by melvinzhang** [comment]
Good point about the connection with random generator. Perhaps the choice to select a card pool is only shown when the player chooses one of the random deck generator. i.e. when the player's deck is a random generator the option to select the pool appears. Essentially the pool is a parameter of the random deck generator. Each player can even have different card pools.

**Comment by ShawnieBoy** [comment]
>Each player can even have different card pools.

Although probably best to have them mirroring each other by default, unless you edit the AI's card pool.

**Comment by lodici** [comment]
> Essentially the pool is a parameter of the random deck generator. Each player can even have different card pools.

If that is acceptable then yes that would be the way to go - a card pool for each player instead of the duel as a whole.

**Comment by melvinzhang** [comment]
On the other hand, when I think about how someone would approach it, it seem that the pool would come first before the deck generator.

For example, when I start to play, I would decide I would only want to see cards in Modern, cause that's the format I play in real life. Then I want to choose a deck that fits this format. So an alternative would be you would choose a pool, then the decks shown are only those that conform to that card pool. Eg for prebuilt decks only those with modern cards would appear in the selector.

**Comment by lodici** [comment]
> Eg for prebuilt decks only those with modern cards would appear in the selector.

That would be more consistent and feels intuitively better. You want to write the code for identifying the decks compatible with the selected card pool?

**Comment by melvinzhang** [comment]
Would that simply be a call to isDeckLegal?

**Comment by melvinzhang** [comment]
On the other hand fixing the pool first, doesn't address the issue with deck editing. In this case, does that mean in the deck editor's "card pool" tab only Modern cards would show up? Should there be a way to modify the card pool after creating the new duel, say on the Duel screen where players decks are shown?

**Comment by lodici** [comment]
> Would that simply be a call to MagicFormat.isDeckLegal? (assuming cubes get integrated into MagicFormat)

Yes, I think that would work although I am not sure how efficient it is - every time you change the card pool it would have to load each of the prebuilt decks to determine whether it can be included in the selection list. Potentional performance or memory issues?

**Comment by lodici** [comment]
> In this case, does that mean in the deck editor's "card pool" tab only Modern cards would show up? Should there be a way to modify the card pool after creating the new duel, say on the Duel screen where players decks are shown?

No, I think that would be confusing and inconsistent. I would hide the Formats filter button in this case. If you want to change the card pool then you would need to return to the duel setup screen. This is actually one of the areas I would like to streamline in the UI - instead of the two "page" setup we have now I would prefer something more like #143.

**Comment by melvinzhang** [comment]
Not going to fix. Leave it to #143.
