### ISSUE TITLE
Build server is timing out.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#388]
A number of recent builds (including the [latest](https://buildhive.cloudbees.com/job/magarena/job/magarena/1459/)) all seem to have stopped at 2 hours exactly with grey status indicators (the console out says aborted). The fact that they are all 2 hours looks like some sort of timeout.

In general the time it takes to do a build is ridiculous - I am pretty sure this is not how CI is supposed to work. Why can't we have different build configurations - one with a comprehensive test that is run once per day at a scheduled time and another with none or a much smaller testing pool that is triggered on a commit.

Also is there some indication that the build artifacts associated with an aborted run are the correct ones and not just the last successful ones?

**Comment by melvinzhang** [comment]
Thanks for bringing this up, it should not timeout unless the AI goes into an infinite loop which needs to be fixed. buildhive do not support multiple configurations, you can enable CI for a project and it will run a build script whenever it detects changes. The main purpose for this is to test the cards in simulated games to check that they do not crash the program. It runs 100 games which takes around 1.5hrs on the build server. 

If you want to get the zip files without running the crash tests, you can "make zips" on Linux. Alternatively you can clone the project and create a new for your clone that runs "make zips" instead of "make buildhive".

**Comment by lodici** [comment]
> If you want to get the zip files without running the crash tests, you can "make zips" on Linux

Thanks that is useful to know.

**Comment by lodici** [comment]
Also, seem to be getting more of these recently...
![screenshot00193](https://cloud.githubusercontent.com/assets/2443519/8764635/1a23cf8c-2dde-11e5-9fa1-2df5567eca55.png)

**Comment by melvinzhang** [comment]
Not much we can do about it. This means the service is waiting for a machine to pick up the job. Buildhive probably only has a small set of machines running all the builds, when the number of build requests exceeds the number of machines, the build needs to wait for the machines to become available.

**Comment by lodici** [comment]
Hmm, except I wonder whether they have downgraded Magarena jobs on account of the timeouts and possibly the high cpu usage when running test duels using MCTS.

**Comment by melvinzhang** [comment]
Could be but I doubt it. You can see the status of the build machines at https://buildhive.cloudbees.com/view/My%20Repositories/ There is only one machine to serve all the buildhive builds and it is currently building the Pike language.

**Comment by lodici** [comment]
I find it hard to believe Magarena is the only other job in all build queues. _Unless_ it is the only other job on this specific build server (the old, crap one in the corner). Or my assumption of how busy cloudbees is way out.
