### ISSUE TITLE
pending triggers should go on the stack in APNAP order

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#423]
raised in [forum](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17490&sid=09fbb0f886879abbab010e7f936824e6#p184062) by sponeta.

Shape Stealer shouldn't get the bushido bonus of a creature it's blocking.

**Comment by ShawnieBoy** [comment]
More of a stack and priority issue, bushido and Shape Stealer go onto the stack automatically. The non-active player's turn will be added last and so resolve first.
Blocking requires you to be the non-active player (You can't block on your turn, only someone elses), so if the Shape Stealer blocks it doesn't get the bonus as it resolves before bushido does.

I'm guessing that if this isn't occurring, it's due to the order entering the stack is wrong.
