### ISSUE TITLE
That Which Was Taken can target Humble Budoka even though it has shroud.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#424]
raised in [forum](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17490&sid=09fbb0f886879abbab010e7f936824e6#p183993) by sponeta.

**Comment by ShawnieBoy** [comment]
I think this is due to the custom target choice for 'target permanent other than SN' - would have thought it would still take into account shroud, but apparently not...

**Comment by melvinzhang** [comment]
Problem is the description on https://github.com/magarena/magarena/blob/5ebbad2a3b625bdf1f5ecc814f2e75e92a192618/release/Magarena/scripts/That_Which_Was_Taken.groovy#L12 uses "a permanent" instead of "target permanent".

Can be implemented with MagicTargetChoice.PosOther now, see https://github.com/magarena/magarena/commit/38ceb777bb42308d91e82e09dc06b5e502d58d90

**Comment by ShawnieBoy** [comment]
:+1: 
Thanks, totally missed that!
