### ISSUE TITLE
Stoneshock Giant's ability should affect creatures that come into play after monstrous

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#443]
should affect all creatures the opponent controls even if they come into play after the monstrous is used for that turn.  Currently if you cast a creature after the monstrous ability has ben used that turn it can block.

**Comment by ShawnieBoy** [comment]
This may have to be fixed via a groovy script as it's creating a game level change instead of a normal effect. e.g. 'creatures you control get +1/+1 this turn' doesn't effect creatures you cast later that turn.

Essentially, Stoneshock Giant should gain the ability: "Creatures without flying your opponents control can't block." for this turn.
