### ISSUE TITLE
Replace missing image with proxy image

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#453]
Currently, it is not possible to play a game if card images are missing since it represents all missing images using a single generic image. This also affects the deck and sample hand views as well which are completely unusable, while exploring the new BFZ set which currently has no images is not particularly useful either. 

So with a view to fixing these issues as well as a possible replacement for the unsupported and increasingly dated text mode I have distilled some of the work @ShawnieBoy  and I have done on the CardBuilder project to create a proxy image generator which produces a simple textual representation of a card. Once the proxy image is created it is cached and treated just like a normal card image.

Note this is not an alternative to CardBuilder and no effort has been made to replicate the look of the various card styles - it designed to be a more practical replacement for the existing missing image.

![screenshot00330](https://cloud.githubusercontent.com/assets/2443519/10197154/2ad1d2c2-678e-11e5-9299-37b8c0318f90.png)

see 472ad23edb8d6a37638a8811d456da1825679a08 for changes.

**Comment by ShawnieBoy** [comment]
I think this could be a good opportunity to get cardbuilder more integrated to the main build.
I've had a small fiddle with the cardbuilder but since the repository move and other changes to the ui, I've not been able to get it working.

The card builder can already produce proxies where the frame style isn't relevant (It will default to a basic frame).

@lodici Would you be able to have a look it it again? Lots of UI elements have been renamed/refunctioned and I'm not entirely sure how it all slots together.

Maybe a Card Builder beta for next release? (With a double bonus if I can get the new devoid frames involved as well.

**Comment by lodici** [comment]
> @lodici Would you be able to have a look it it again? Lots of UI elements have been renamed/refunctioned and I'm not entirely sure how it all slots together.
> 
> Maybe a Card Builder beta for next release? (With a double bonus if I can get the new devoid frames involved as well.

If I have time I will take a look - I want to work on downloading images on demand this session and possibly learn about bundling a JRE using packr (see #448) although I am not sure whether @melvinzhang might already be looking into that, it is quite an interesting challenge. There are also a couple of issues associated with the recent log update on my TODO list as well.

**Comment by melvinzhang** [comment]
@lodici No, I'm looking into #448 Focusing on fixing the concurrency bugs surfaced by the new CI.

**Comment by lodici** [comment]
Ok thanks - I assume you meant "not looking".

**Comment by melvinzhang** [comment]
Correct, "not looking".
