### ISSUE TITLE
-Xmx in Magarena.command (Mac) set to 256. Should be 512?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#492]
On Windows (.exe) and Linux (.sh) it is 512. It is not difficult to get a ``java.lang.OutOfMemoryError: Java heap space`` when running with 256 on Windows (I got it browsing cards in the Explorer). Presumably it would be the same for the Mac.

**Comment by melvinzhang** [comment]
I think the Magarena.command file is no longer used and should be removed, it was used before we created the Mac specific distribution zip and users had to manually extract the package and launch via the command file.

The current Mac distribution behaves like a native app and can be dragged to the dock and started directly because it has the necessary folders and property files. It is configured to start by executing Magarena.app/Contents/MacOS/MagarenaLauncher.sh which I just noticed is calling the exe instead of the jar...

**Comment by lodici** [comment]
Thanks for the clarification - I agree the command file should go as it is a tad confusing.

**Comment by melvinzhang** [comment]
From what I can tell, the Mac package now doesn't work as the launcher is trying to start via the exe. On Linux, it fails with "Error: Invalid or corrupt jarfile Magarena.exe" Strange that no one has reported this yet, should have started since July release.

**Comment by melvinzhang** [comment]
Perhaps users were using the command file instead? Anyone using MacOS able to test the current release?

**Comment by lodici** [comment]
I can confirm that the last version of Magarena to work with the launcher was 1.63. In 1.64, we extracted the ``jar`` from the ``exe`` and the only way to run it was to open the package and use the ``command`` file (with its Xmx limitations). I can also confirm that the above fix works for the latest build and so would recommend updating the download link asap.

**Comment by melvinzhang** [comment]
1.67 mac download link updated with above fix, please help to test it, thanks!

**Comment by lodici** [comment]
:+1: Worked perfectly.
