### ISSUE TITLE
Bad play simple test: Ai loses because it does not block.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#500]
Whilst looking into the blacklist mechanism (see #496) I was trying to think of an initial test that might catch the flying-on-flying play mentioned. I ended up getting a bit diverted after creating the following very simple test (see attached save game file). Basically, the gameplay I would expect (unless I am missing something) is -

1. I and the AI each have one health.
2. I have a single 1/1 flying card in play which I attack with.
3. AI has a 2/2 non-flying card in play __but__ has [Jump](http://static.tappedout.net/mtg-cards-2/2010-core-set/jump/jump.jpg) in hand.
4. AI should play Jump and give the 2/2 flying.
5. AI blocks, kills my card.
6. Next turn AI attacks and wins.

What I found was that all AIs _except MCTS_ did nothing and lost the game. However, having played Jump, MCTS did not block and lost the game as well!

I think if we can figure out how to get the AIs to win this very simple scenario we might have a better understanding in addressing some of the issues raised in #496.

[AiLosesCauseItWontBlock.game.txt](https://github.com/magarena/magarena/files/33870/AiLosesCauseItWontBlock.game.txt)
_This is the ``game`` file. Save to ``saved_games``, remove ``txt`` extension (only way to attach it here on Github) and you can load from the main menu if running in dev mode. Alternatively it should be clear enough if you want to set up an equivalent test class._

**Comment by ShawnieBoy** [comment]
This is down to the known 'AI panic' when it's losing. #228 #235

It could be a scenario where it perceives it's imminent win too highly, you've attacked with a 1/1, leaving yourself open, meaning that it doesn't need to respond, it can attack and win next turn. Not taking into account it would have already lost by then.

Would be interesting to see this scenario in regards to losing via poison instead of life - in case low life levels causes this 'panic'?

**Comment by lodici** [comment]
The ironic thing is that if this occurred in an actual game (and you did not know what is in the AI's hand) the MCTS's decision to give the 2/2 card flying (good) but then not block (bad) makes it look even worse than the other AI's which simply did nothing - you would just assume that these AIs had no way out. 

Given such a simple game state, I can't believe that MCTS did not run a game simulation with the winning steps as described above. Your point about it not taking into account health seems apposite.

**Comment by melvinzhang** [comment]
Great test game, this is exactly the sort of thing we need to make progress. A clean reproducible AI bad play. I can confirm the bad behavior. Initial investigation looks like the AI did not get a chance to declare blockers after playing Jump.

**Comment by melvinzhang** [comment]
Turns out the problem is with timing restriction. Jump is tagged with timimg=pump, and pump => can only be used during your first main, declare blockers, and as response. Therefore the AI has no options to cast it during declare attackers. The Jump that was cast is AFTER blockers have been declared, hence it did not affect blocking choice (the AI could not block since its creature did not have flying when it needed to declare blockers). 

The fix is to allow pump to be used during "declare attackers". So that after the opponent declare attack and BEFORE declare blockers, the AI can cast Jump. With this change MCTS is able to detect that the given game scenario is an AI win and it executes the win correctly.

**Comment by melvinzhang** [comment]
@lodici perhaps next time commit the file to the release/Magarena/saved_games folder, it is good to keep a copy of these game scenarios as regression tests.

**Comment by lodici** [comment]
> @lodici perhaps next time commit the file to the release/Magarena/saved_games folder, it is good to keep a copy of these game scenarios as regression tests.

That is not going to work, I have loads of game files stored here which we don't want cluttering up the repository. Maybe use the new ``reports`` folder as part of the new Gameplay Report to store test scenarios. Or create a new ``magic.ai.tests`` package and put them there. You don't really want to be including them in a release do you?

**Comment by melvinzhang** [comment]
The only folders included in a release is avatars, decks, sounds, scripts, scripts_missing, translations. Now that I think about it a more, putting it in the release folder may be confusing, the tests folder is a more appropriate place.

**Comment by melvinzhang** [comment]
The problem is that the running application should only have access to the release/Magara folder (DATA_PATH) and not outside of it, so by putting in saved_games, it is automatically detected by the application. The plan is to have this in the repo for devMode loading, it is only for someone who clones the repo, it will not be in a release zip.

**Comment by lodici** [comment]
In that case, like the decks folder, we should create a separate folder to keep user and public games separate. At the moment a source-controlled ``game`` will overwrite a local with the same name. This will also require updating the UI to facilitate selecting between private and public games.

**Comment by melvinzhang** [comment]
"git pull" will not automatically overwrite a file on checkout, it will instead not update your working directory to master. This will only occur when the filename are the same, which should be not that common as long as we use descriptive file names.

**Comment by lodici** [comment]
Regardless, it has the potential to be messy. I am not keen on mixing public and private game files. They should be kept separate.

**Comment by lodici** [comment]
Good to see all AIs now beat me no problem. What is interesting is that MMAB and MCTS play very quickly but VEGAS is much slower, using all available 8 seconds thinking time for each step.

**Comment by melvinzhang** [comment]
perhaps a separate source controlled test_games folder for specially crafted game files (like this AI test file) vs user generated ones in saved_games?

**Comment by lodici** [comment]
Yep, that would work.

**Comment by lodici** [comment]
> What is interesting is that MMAB and MCTS play very quickly but VEGAS is much slower, using all available 8 seconds thinking time for each step.

Tried all AIs with 1 second thinking time. All beat me again, but this time VEGAS was on a par with the other two. So it would seem VEGAS is much more sensitive to the level selected which is useful to know.

**Comment by melvinzhang** [comment]
I think VEGAS always use all the time because it doesn't detect the winning line. MMAB and MCTS is able to stop once it finds a winning line of play.

**Comment by lodici** [comment]
![screenshot00360](https://cloud.githubusercontent.com/assets/2443519/11163290/13726ec4-8ac1-11e5-8e52-0268271ecb15.png)

Decided to go for simple UI since it is only devMode - Game File opens a standard file dialog in the data directory where you can select either of the above directories. Test class lets you select a class from magic.test package.

**Comment by lodici** [comment]
You can now add a description to the top of a ``game`` file and it will be displayed in the open file dialog...
![screenshot00361](https://cloud.githubusercontent.com/assets/2443519/11163381/deb8465a-8ac4-11e5-9d52-74d0d36ad52d.png)
