### ISSUE TITLE
Can't download basic land card images

### ISSUE THREAD

**Issue by tlorance** [magarena/magarena#515]
For some reason, when I updated from 1.62 to 1.67, the image updater acquired everything but the basic five card images.  The image files are in the card images folder in the app package, but it throws this error when it runs:
"java.io.FileNotFoundException: http://magiccards.info/scans/en/bfz/274.jpg [Forest.jpg]
java.io.FileNotFoundException: http://magiccards.info/scans/en/bfz/259.jpg [Island.jpg]
java.io.FileNotFoundException: http://magiccards.info/scans/en/bfz/269.jpg [Mountain.jpg]
java.io.FileNotFoundException: http://magiccards.info/scans/en/bfz/254.jpg [Plains.jpg]
java.io.FileNotFoundException: http://magiccards.info/scans/en/bfz/264.jpg [Swamp.jpg]"

**Comment by ShawnieBoy** [comment]
Magiccards.info has since renumbered the basic lands to take into account full-art images.
Renaming the links to end in 'b.jpg' will fix this ie  http://magiccards.info/scans/en/bfz/274b.jpg

**Comment by lodici** [comment]
@tlorance as @ShawnieBoy mentioned since 1.67 was released the links were replaced by ``magiccards.info``. We will update them for 1.68 but if you want to get rid of the new images alert before then you can do so manually as follows -
- Open Card explorer from the main menu.
- Select the Type -> Basic filter to restrict the cards list to basic lands.
- For each basic land...
 - Double click to open the script view.
 - Click the file path displayed at the top of the screen to open the script in your system's default text editor.
 - Update the image link as described above and save.

Restart Magarena and download the images to remove the alert.

**Comment by lodici** [comment]
Links updated in 1.68.
