### ISSUE TITLE
Cards smaller?

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#541]
It could just be me, but are the cards on the battlefield smaller than before? It could just be my eyes, but I was sure I could read their text (just about), but it's all too small/blurred now.

Just a wondering with the card image adjustments going on.

**Comment by lodici** [comment]
Took a screen shot of the gameboard for a given test running in different versions then flicked back and forth between the images. I could see no discernible difference between 1.68 and the latest build.

**Comment by ShawnieBoy** [comment]
Thanks for checking - it is just me then, hehe.

I guess there must be just a feeling that the cards could be bigger, but I know that becomes an issue for those in lower resolutions.

**Comment by ShawnieBoy** [comment]
![cardsize](https://cloud.githubusercontent.com/assets/2363180/11567209/dbc5d976-99dd-11e5-9c01-472d40e0e7f3.png)

This is the windowed size I normally play at, not full screen as I'm normally switching between code etc.

**Comment by lodici** [comment]
I remember someone mentioned in the forum about being able to zoom in on the game board. If the game board was a pure image instead of a load of Swing components then that would be something fairly easy to do.

The problem is that although you have a lot of horizontal space there is very limited vertical space to resize cards and retain their aspect ratio. A possible solution could be an option to temporarily maximize a particular zone. You can kind of do that now by clicking on a player zone button, although you can't play from the zone screen and it does not work for the permanents area.

**Comment by lodici** [comment]
BTW, the player panels look like they are greyed out - or is that just your color scheme? The play and undo buttons kind of stick out!

**Comment by ShawnieBoy** [comment]
>BTW, the player panels look like they are greyed out - or is that just your color scheme? The play and undo buttons kind of stick out!

I think that's just the colour scheme.

I think I was just misremembering wrong - The vertical space is at a premium really, and I think we've covered the issues with having a combat zone hide and appear, and having to redraw cards that have been moved or reposition.
