### ISSUE TITLE
AI activation limit should not be applied to human player

### ISSUE THREAD

**Issue by itandetnik** [magarena/magarena#551]
I have `Puresteel Paladin`, `Auriok Sunchaser`, `Mask of Avacyn`, and enough artifact lands to get *Metalcraft*. All lands are currently tapped (so no mana source).

In M1, I equip `Auriok Sunchaser` with `Mask of Avacyn` and attack. The expectation is that, in M2 after the attack, I would be able to switch the equipment over to `Puresteel Paladin`, for defense. But the computer won't let me - after the attack, it skips M2 and goes straight to opponent's turn. It's as if `Equip 0` doesn't count as an effect worthy of prompt.

Tried to attach gameplay-report.zip, but for some reason Github won't accept it: "Unfortunately, we don’t support that file type."

**Comment by lodici** [comment]
> Tried to attach gameplay-report.zip, but for some reason Github won't accept it: "Unfortunately, we don’t support that file type."

It was designed really for posting on the forum since that seems to be where most of the gameplay issues are reported. Could you attach the zip to a new post in the [Bug reports for Magarena 1.68](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17929&sid=b1a30ed8eaa32cde8776b1b955519288) thread?

**Comment by itandetnik** [comment]
[Duly posted.](http://www.slightlymagic.net/forum/viewtopic.php?f=82&t=17929&p=189751#p189751)

Update: I turned off "Automatically pass priority" in Preferences. With this, I do get priority at M2 - but `Mask of Avacyn` is not highlighted (nor is any other card), doesn't react to clicks, and so still can't be moved over to `Puresteel Paladin`. The only available action is *Pass*.

**Comment by itandetnik** [comment]
Curiouser: if I leave the equipment attached to `Puresteel Paladin` and have `Auriok Sunchaser` attack without, then in M2 it can be switched - but only once. Could this be related to #147 ? The resolution there was to restrict AI to switch no more than twice per turn - is it possible that the limitation also gets applied to the human player? "Limit options for human player..." preference is unchecked.

**Comment by itandetnik** [comment]
Playing with this further after getting more equipment cards, I'm convinced that there's a limit of two `Equip 0` actions per equipment per turn, applied to the human player.

**Comment by ShawnieBoy** [comment]
Thanks for uploading the TestGame - Duplicated all the issues and does appear to be a usage restriction applying to the 0-cost activation, similar to #341 

This could be due to the cost being applied via a groovy code.

Another thing worth double checking, is that the Equipment have two Equip costs with Puresteel Paladin in play, It could be possible that the activation restriction is only being applied for one of these.

**Comment by melvinzhang** [comment]
Yes, this is because the AI activation limit is also applied to human player.
