### ISSUE TITLE
Add option to download crops in download images dialog.

### ISSUE THREAD

**Issue by lodici** [magarena/magarena#582]
The download images dialog should be renamed to "Images Manager". A new setting "Images Source" should be added with the following options -

- _None_: use proxy images with no art. Disables new images alert. Disables image download options.
- _Proxy images_: uses proxy images with downloaded cropped art.
- _Original images_: uses download full card image scans. Default.

"Images Source" will be a global setting which will affect any place where an image is displayed. 

Cropped images can be treated in the same way as the full images since it is effectively the same image url with ``http://magiccards.info/scans/...`` replaced by ``http://magiccards.info/crop/...``. The global setting will determine which images are downloaded and folder scanned for displaying the new image alert. What about non-``magiccards.info`` crop urls? Would need to add a crop url to script.

Cropped and full images will use the same root images folder with crops having their own sub-folder. _What about tokens_? Not sure.

Even when Original/cropped images are used CardBuilder will still automatically be used for generating art-less proxies for missing images.

**Comment by ShawnieBoy** [comment]
Wow, never knew magiccards had crops. Was kinda hoping to sidestep the whole script url thing entirely :cry: 

Images for proxies are not as game-breaking as not having an image on a card at all, as it contains all the information necessary to play (as per the old proxies) - As proxy cards are not default, if some images don't appear, that could end up being a user choice for cropped images.

As these images don't effect card text, it doesn't matter which version of the art is used, instead of it being dictated by us which image to use (same as the override folder).

Non-standard image sizes - Tokens, Planewalkers etc. Haven't been implemented yet, not even with replacement magarena images.

**Comment by lodici** [comment]
![screenshot00454](https://cloud.githubusercontent.com/assets/2443519/12866555/869fe86e-ccc9-11e5-89fb-1ac481e45cb5.png)

09d5e2b8731652eb08176dba6b03e9c2eb587f23 adds the option to download cropped images. It is pretty rudimentary but should get the job done. The above screenshot shows the number of crop images still missing after running the download (out of 10,509 playable and 5,062 unimplemented) which is not too bad at all.

**Comment by melvinzhang** [comment]
If this is ready for 1.70 release, please help to update the release/README.txt. Thanks!

**Comment by ShawnieBoy** [comment]
Just something I've noticed with the latest update to magiccards image quality - it looks as though the image_updated will be relevant for cropped images when quality changes.

If crops could be updated via image_updated that would be great :grinning:

**Comment by lodici** [comment]
> Just something I've noticed with the latest update to magiccards image quality - it looks as though the image_updated will be relevant for cropped images when quality changes.
> 
> If crops could be updated via image_updated that would be great :grinning:

I have added #739 to address this. So can close this issue.
