### ISSUE TITLE
Mana cost reduction and {X}{X}

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#616]
With Etherium Sculptor in play, (Artifact spells cost you {1} less to cast), You're unable to cast Chalice of the Void 'for free'.

Most likely due to the restriction of X not being able to be 0, even though it's actually 1.

So unable to set a value for X higher than the amount of mana available (0)

**Comment by melvinzhang** [comment]
Thanks for play testing the new cards! I'm able to replicate the bug.

**Comment by ShawnieBoy** [comment]
No problem - there's a few things I have in mind to check :grinning: 

Cost manipulation is one of my favourite things in mtg - getting stuff for free is always good!

**Comment by melvinzhang** [comment]
Found the bug, was a rather serious one, modCast was only applying the last modification instead of all of them. So the case of 2 Etherium Sculptor got treated as if there is only one cost reduction effect in play. Now with 2 Etherium Sculptor, you can cast Chalice for X = 1 without paying any mana.
