### ISSUE TITLE
Log doesn't show payment of {0} for cards with casting cost {0}

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#640]
Opposite of #636 

Permanents with a casting cost of {0} are shown in the log as simply being 'put into play' without casting. Payment of {0} should be shown, but not payment of NONE.

**Comment by melvinzhang** [comment]
The removal of payment of {0} is not to deal with NONE, it is to handle alternate costs without mana cost, eg "Force of Will" and cost increase. Each alternate cost without mana cost is given an additional {0} mana cost so that it can be increased by cost increase effects, eg "Spells cost {1} more to cast" but we don't want these to show in the log unless it was increased by an effect.

**Comment by melvinzhang** [comment]
The way I got around this is to avoid showing "Pay {0}" at all, I understood at the time this would have the effect that knowing that permanents with mana cost {0} will also not be shown but I felt it was a reasonable trade-off to solve the "Force of Will" showing "Pay 1 life, exile a blue card, pay {0}".

**Comment by melvinzhang** [comment]
Turns out MagicManaCost.NONE is a good way to record these "virtual" mana costs added for the purpose of interaction with cost modification.
