### ISSUE TITLE
Deck Statistics panel text is missing/invisible.

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#644]
Could be an issue with the theme I'm using (Dream of Grey)

![deck stat](https://cloud.githubusercontent.com/assets/2363180/12358055/5160d35c-bba3-11e5-8e67-3ffd941fbf24.png)

**Comment by lodici** [comment]
Unable to replicate using Dream of Grey. Which screen was this, this panel is used in a few places.

**Comment by ShawnieBoy** [comment]
It's the deck screen when you start a new duel, and also in the deck builder. I think it's because the other text is rendered white, and this is white on white.

**Comment by lodici** [comment]
> I think it's because the other text is rendered white, and this is white on white.

Not sure what you mean - have you manually tweaked the theme? As I say the stats panel text is all black, present and correct when I used the downloaded Dream of Grey theme.

**Comment by ShawnieBoy** [comment]
Looking through it - I must have edited it in the past. I think I remember the headers were all black on black so the color was changed.

**Comment by lodici** [comment]
I actually removed the theme-color text for the new look, now it will always be black text on translucent white background. One less thing to worry about!

**Comment by ShawnieBoy** [comment]
Ahh, I see - I'm really liking it too! Mana curve is so much easier to see. Could possibly have the deck description be able to collapse too, or even collapsed as default as not many decks have descriptions

**Comment by lodici** [comment]
If the screen is big enough then the sidebar is designed to fill the vertical space with the description viewer expanding to fill any remaining space available after the image and stats viewer claimed the space they need. There are still a few issues with how the desc viewer resizes if there is not enough space which I will look into but I felt that it is better to have it with some minor niggles since it allowed to me update and greatly simplify the duel decks screen.

Eventually I would like to make the desc viewer editable so that a user can add notes, comments or update the description.
