### ISSUE TITLE
Option to speed up progression through the stack

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#699]
When the stack gets very full with triggers, it does take a while to progress through them all when you're unable to respond.

Could there be an option to speed this up or even make it instant?

**Comment by lodici** [comment]
You can adjust it using the poorly name _Message_ setting -
![screenshot00476](https://cloud.githubusercontent.com/assets/2443519/13143475/20109216-d63c-11e5-8e13-ba9c65d3f00c.png)
For the odd case we could always add something like a "purge" button to the stack header that when clicked would temporarily set the _Message_ setting to zero.
![screenshot00477](https://cloud.githubusercontent.com/assets/2443519/13143556/9a1c50b8-d63c-11e5-90d0-b523657290a1.png)

**Comment by ShawnieBoy** [comment]
Ahh, cool didn't realise that - Yes, having a 'purge' would be handy too. Sometimes you just want to know how it all ends, hehe

**Comment by ShawnieBoy** [comment]
Actually, having the message time decrease as it progresses through many items on the stack could work.

**Comment by ShawnieBoy** [comment]
Brainwave - Could use this to detect game loops! - if the time then decreased down into a high negative number, that could show that a loop is in progress.

**Comment by lodici** [comment]
@ShawnieBoy, @melvinzhang please can you suggest a test class/scenario I can use that will fill up the stack. Thanks.

**Comment by ShawnieBoy** [comment]
Or if you want a loop - [Mindcrank](http://magiccards.info/nph/en/144.html), [Duskmantle Guildmage](http://magiccards.info/gtc/en/158.html) (activate first ability), then do 1 damage and you're away. 😁

**Comment by lodici** [comment]
Shows stack count (3db948116c199d0c82f7c9ebc48351af9599e6a3).

**Comment by lodici** [comment]
![screenshot00558](https://cloud.githubusercontent.com/assets/2443519/21864772/39487058-d83b-11e6-8a6d-6db9faac9d71.png)
Click on the Stack titlebar when the fast-forward icon is displayed to skip the stack item delay. It is not as instantaneous as I expected because I think the AI does some thinking each time a stack item is played. For reasons I have yet to fathom if you run a visual AI vs AI game it fairly flies through the stack, much quicker than running a normal human vs AI game.
