### ISSUE TITLE
card viewer does not use image cache, always load from file on disk

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#733]
Scrolling back and forth over the same cards in card explorer loads the same images over and over again.  This is due to CardViewer.getImage calling MagicImages.getOrigSizeCardImage. Should call MagicImages.getCardImageUseCache.

@lodici is there a special reason for bypassing the image cache in card viewer?

**Comment by lodici** [comment]
With the explorer I found that a cache makes no discernible difference to the displaying of a card image. Most of time it will be just adding an image to the cache and wasting memory. And what would be an optimum size cache for the explorer anyway? Unlike the deck editor where there is a limited set of cards and where you are more likely to display the same card image much more frequently especially with the sample hand and tiled card image screens. Likewise during a game.

**Comment by melvinzhang** [comment]
CardViewer is also used to load images for the deck viewer and deck editor where it makes sense to use the cache as you've described. I'd also like to simplify the API for MagicImages to only one public method getCardImages that always use cache instead of two methods: getOrigSizeCardImage and getCardImageUseCache.

**Comment by melvinzhang** [comment]
@lodici the problem is in card viewer not explorer, explorer is one of the components that use card viewer. The other two are are deck viewer and deck editor. Viewing cards in deck viewer and deck editor is more common than explorer, especially the deck viewer which is on the duel screen.

The current two methods can be confusing for clients of MagicImages, they have to explicitly declare whether they want to call getOrigSizeCardImage or getCardImageUseCache. 90% of them use getCardImageUseCache and only card viewer use getOrigSizeCardImage. It would simplify the code and we can use shorter method names if there is only one method, getCardImage.

**Comment by lodici** [comment]
> @lodici the problem is in card viewer not explorer, explorer is one of the components that use card viewer. The other two are are deck viewer and deck editor. Viewing cards in deck viewer and deck editor is more common than explorer, especially the deck viewer which is on the duel screen.

You are entirely missing the point I was making in my original reply. I know what does what having written the code. The problem _is explorer_ because I don't think a cache makes much sense on this one particular screen as explained above.

> The current two methods can be confusing for clients of MagicImages, they have to explicitly declare whether they want to call getOrigSizeCardImage or getCardImageUseCache.

That is because they do two different things?!? One uses the cache and the other doesn't. I think that is pretty clear. I admit the the methods could do with renaming, getCardImage instead of getCardImageUseCache would be better definitely. getSourceImage instead of getOrigSizeCardImage maybe.

>  90% of them use getCardImageUseCache and only card viewer use getOrigSizeCardImage. It would simplify the code and we can use shorter method names if there is only one method, getCardImage.

Utlimately, although I don't think there is much benefit to having a cache on the explorer if you are set on implementing a one-size-fits-all approach using a single method then it is probably not going to have any significant effect on the the explorer either way, so go ahead.

**Comment by melvinzhang** [comment]
My bad, I thought you were misled by my first comment which only mentions the explorer. In retrospect, I should have also mentioned the benefits for deck viewer and deck editor in using the cache.

The issue is much clearer now. Deck viewer, deck editor, and explorer uses CardViewer and does not use the cache at the moment. Using cache would benefit deck editor and deck viewer but no significant effect on explorer.
