### ISSUE TITLE
Incorrect interaction between Living Lands and Evil Presence

### ISSUE THREAD

**Issue by melvinzhang** [magarena/magarena#754]
AI cast Living Lands. I cast Evil Presence on one of AI's Forests. Expected result: Forest stops being a creature. Observed result: Forest was put into graveyard.

**Comment by ShawnieBoy** [comment]
This is actually an interesting interaction.
With timestamp order, Living Lands turns Forests to Creatures and sets the P/T to 1/1 first.
Then Evil Presence changes the Forest into a Swamp, but doesn't remove Creature type.

> Setting a land’s subtype doesn’t add or remove any card types (such as creature) or supertypes (such as basic, legendary, and snow) the land may have.

So it becomes a Swamp Creature 1/1. I'm wondering if the effects of Living Lands is setting the P/T later than it should, so that Evil Presence turns the land into a Swamp which doesn't get the P/T set, so is a 0/0 which dies.

**Comment by ShawnieBoy** [comment]
Ok, breaking this down: 

__1st Living Lands, 2nd Evil Presence__
Layer 4 (Type/Subtype Changing Effects): `Forests are Creatures` then `This land is a Swamp` = Swamp Creature 0/0
Layer 7C (P/T Setting Effects): `Forests are 1/1` = Swamp Creature 0/0

Layers done = Swamp Creature 0/0 -> Dead

__1st Evil Presence, 2nd Living Lands__
Layer 4 : `This land is a Swamp` then `Forests are Creatures` = Swamp
Layer 7C `Forests are 1/1` = Swamp

Layers done = Swamp

Not a bug.

**Comment by ShawnieBoy** [comment]
Side-note: Dependecy isn't able to be implemented #758
