### ISSUE TITLE
End of line format

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#77]
I'm assuming that it's still Unix endings, not Windows for end of line? Just want to check that it's my editors being naughty and not something that's changed with file submissions from Firemind or something.

**Comment by lodici** [comment]
Yep, still Unix endings.

**Comment by melvinzhang** [comment]
I think at some point Mike fixed firemind submission to use unix line endings, it was previously using windows line endings. The indentation is also 4 spaces per level and not tabs, there was an issue with Spiritual Sanctuary using a mixture of tabs and spaces. Fixed in https://github.com/magarena/magarena/commit/1ee47162279d410c3ee46048f30789ddf374266c?diff=split

**Comment by ShawnieBoy** [comment]
Thanks - need to fiddle with my settings

**Comment by ShawnieBoy** [comment]
Just so I'm not going crazy, can someone verify the format of the line endings for _ther_Burst.txt in the scripts missing folder. I'm getting Windows endings for lots in there, want to make sure it's really there and not just me! (These settings are annoying me now)

**Comment by ShawnieBoy** [comment]
Ok, it's me - Grr
