### ISSUE TITLE
Becomes Blocked

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#785]
Been working on spells that block creatures, and found that those creatures do not have their 'becomes blocked' triggers activate, even though their states have changed (And these triggers are not 'becomes blocked by a creature'

I'll push what I've put together so far if someone wants to take a look.

**Comment by ShawnieBoy** [comment]
Added a TestBlockTriggers to demonstrate 01677fe3dda6c9dcc55c292f5fea663ff988dcdd

**Comment by melvinzhang** [comment]
That is because BecomesBlocked is not a BecomesState trigger as it predate the creation of BecomesState. The fix would be to make it an instance of BecomesState.

**Comment by melvinzhang** [comment]
The method of triggering will also have to change, instead of DeclareBlockerAction invoking the executeTrigger, SetBlockerAction should be changed to use ChangeStateAction

**Comment by ShawnieBoy** [comment]
Looks like this would also affect the WhenAttacksUnblocked trigger as well. I'll have a look through and see if I can reorganise it a bit - Thanks for the extra info, couldn't see where to look.

**Comment by ShawnieBoy** [comment]
Would it make sense for the BecomesBlocked triggers to be BecomesState triggers?

I feel I've wandered into the web of combat once again :cry:  It's BecomesBlocked, BlockedBy all over again!

**Comment by ShawnieBoy** [comment]
AttacksUnblocked triggers after blockers are declared, but spells can make a creature blocked after blockers are declared, so it should only trigger after the fast effects after declare blockers.

**Comment by melvinzhang** [comment]
I see, yes, it would need to trigger later later.

**Comment by ShawnieBoy** [comment]
Might have to come back to this later today, getting myself in a right mess. :confounded:

**Comment by melvinzhang** [comment]
Removed the bug label as that is how blocked always worked, it never use the StateTrigger tech.

**Comment by melvinzhang** [comment]
Did some research on the AttacksUnblocked, it seems that it is not affected by the spell. An attacker is considered unblocked once no blockers are declared for it. Once this occurs the trigger will fire, the trigger does not care about the attacker later becoming blocked.

This is similar to attacking alone trigger, which are not affected by an effect that puts an a permament tapped an attacking later. The attacking alone trigger fires after declare attackers, even though it is possible for another attacker to be made an attacker due to an effect

**Comment by melvinzhang** [comment]
I'm working on updating the BecomesBlockedTrigger in a compatible way, so that no groovy code needs to be changed.

**Comment by melvinzhang** [comment]
The relevant rules for attacks unblocked is "509.1h An attacking creature with one or more creatures declared as blockers for it becomes a blocked creature; one with no creatures declared as blockers for it becomes an unblocked creature." The condition of attacks unblocked is fulfilled as soon as blockers are declared.

**Comment by melvinzhang** [comment]
TestBlocksTrigger is very helpful in making sure things work out right, thanks for creating it! I think we have all that is needed, but I may not have exhausted tried all the scenarios in the test thought. Please check that it works as expected.

**Comment by ShawnieBoy** [comment]
> The relevant rules for attacks unblocked is "509.1h An attacking creature with one or more creatures declared as blockers for it becomes a blocked creature; one with no creatures declared as blockers for it becomes an unblocked creature." The condition of attacks unblocked is fulfilled as soon as blockers are declared.

In that case it would look as though the 'becomes blocked' spells would need to be cast before declare blockers, essentially during the fast effects of 'declare attackers' - Once declared as an attacker, it should be a legal target.

**Comment by ShawnieBoy** [comment]
The full quote of 509.h explains further 

> 509.1h An attacking creature with one or more creatures declared as blockers for it becomes a
blocked creature; one with no creatures declared as blockers for it becomes an unblocked
creature. This remains unchanged **until** the creature is removed from combat, an effect says that
**it becomes blocked or unblocked**, or the combat phase ends, whichever comes first. A creature
remains blocked even if all the creatures blocking it are removed from combat.

**Comment by melvinzhang** [comment]
That was my first impression when reading this as well, but on thinking about it what it is referring to the state of being unblocked. The state can change after declare blockers via the reasons mentioned in the rules.

However, the key is that triggers fire once their condition is true, even if the condition becomes false later. Once blockers are declared, any attacker with no blockers declared is in the state of attacking and unblocked, this causes the trigger to fire. As the rule says, the attacker can become blocked due to an effect, but that doesn't matter anymore as the trigger is on the stack.

**Comment by ShawnieBoy** [comment]
Yes, was reading ahead - is interesting to know as it doesn't work as I've always expected (and how I played in RL games!) - been doing more tests and looks like this is all working as it should.

Thanks again for fixing my mess!

**Comment by ShawnieBoy** [comment]
Combat triggers can be a real head-scratcher, should have learned from my last venture into the blocking/blocked-triggers!
