### ISSUE TITLE
Can't choose zero for things that require a numerical choice e.g. Mirror Entity, Chalice of the Void.

### ISSUE THREAD

**Issue by Muppet1** [magarena/magarena#79]

**Comment by ShawnieBoy** [comment]
I can remember attempting to include this, but I think it's due to the AI - correct me if I'm wrong Melvin

**Comment by melvinzhang** [comment]
This is a design choice that was before my time. My understanding is that it helps to reduce the number of options the AI needs to consider for X. Could be significant if it is X + other cost since the number of options is the (no. options for X) times (no. of options for other cost). And most of the time X = 0 is not a meaningful choice.

**Comment by melvinzhang** [comment]
This one of our game rules, see https://github.com/magarena/magarena/wiki/GameRules
