### ISSUE TITLE
Pollen Lullaby

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#868]
name=Pollen Lullaby
image=http://magiccards.info/scans/en/cmd/26.jpg
value=2.593
rarity=U
type=Instant
cost={1}{W}
ability=Cast SN only during the declare attackers step and only if you've been attacked this step.
effect=Prevent all combat damage that would be dealt this turn.~Clash with an opponent. If you win, creatures your opponents control doesn't untap during its controller's next untap step.
timing=removal
oracle=Prevent all combat damage that would be dealt this turn. Clash with an opponent. If you win, creatures that player controls don't untap during the player's next untap step.

**Comment by ShawnieBoy** [comment]
The ability should be a 'Cast SN with AI' restricting the casting for the player isn't needed. Even the 'only if you've been attacked this step.' is a bit dubious for me, but does help the AI.

**Comment by melvinzhang** [comment]
The "you've been attacked this step" is to ensure you are the defending player, so that the effect can be rephrase as "creatures your opponents control doesn't untap during its controller's next untap step.". The actual oracle text is "creatures that player controls don't untap during the player's next untap step.".

Without this limitation, when cast as the attacker, it should prevent your creatures from untapping but it prevents your opponent's creatures from untapping instead.

**Comment by melvinzhang** [comment]
Hmm, actually in this case replacing "that player" with "your opponents control" is always correct since it is "Clash with an opponent".

**Comment by melvinzhang** [comment]
This needs groovy as it affects creature that ETB after the effect resolves. It is similar to Exhaustion and Mana Vapors. @kelsioboy Feel free to reopen this issue when you submit the groovy script.
