### ISSUE TITLE
Retaliation

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#871]
name=Retaliation
image=http://magiccards.info/scans/en/us/272.jpg
value=3.040
rarity=U
type=Enchantment
cost={2}{G}
ability=Creatures you control have "Whenever SN becomes blocked by a creature, SN gets +1/+1 until end of turn."
timing=enchantment
oracle=Creatures you control have "Whenever this creature becomes blocked by a creature, this creature gets +1/+1 until end of turn."

**Comment by ShawnieBoy** [comment]
Another good find 😁

**Comment by melvinzhang** [comment]
This reminded me of all the times we had to do this manual change. I manage to get the ability parsing to to this automatically in 9535ecfc81efc446 so the original oracle text would work without changes, see 3a4556cc4b. Then I went back and fix the older cards so that they use the oracle text, see 1495c5ea062
