### ISSUE TITLE
Mijae Djinn (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#926]
name=Mijae Djinn
image=http://magiccards.info/scans/en/rv/165.jpg
value=3.562
rarity=R
type=Creature
subtype=Djinn
cost={R}{R}{R}
pt=6/3
ability=Whenever SN attacks, flip a coin. If you lose the flip, remove SN from combat~and tap it.
timing=main
oracle=Whenever Mijae Djinn attacks, flip a coin. If you lose the flip, remove Mijae Djinn from combat and tap it.

**Comment by melvinzhang** [comment]
This will always tap it regardless of result the flip as it is read as "Flip a coin. If you lose the flip, remove SN from combat. Tap it." whereas we want the tap to depend on the flip. The correct way can only be done in groovy code.

It is not easy to spot this since on attack it will already be tap. You can check by adding vigilance to the ability to prevent it from tapping on attack.

**Comment by kelsioboy** [comment]
Sorry, I sent this letter by mistake. I will take more care.
