### ISSUE TITLE
Remove removal values?

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarena#95]
Currently there are around 325 cards with a removal value. I doubt that's all the cards with a removal effect.

I have a bit of a problem with these values as they do seem very arbitrary. How essential are these values for the AI? If they have to remain, what kind of structure should be used to determine these values?

Surely Exile is better than Destroy, but what about non-targeted exile? What would rank a 5? Exile all permanents an opponent controls? Would that then make Exile all permanents a 4? If Destroy would then be 3 or less, what about Bounce or Flicker? Would they both be 1? Even if they effected multiple permanents?

I'd personally press to have these removed, if the AI can already determine the effects of a spell by casting it, there would be no need for a rating system. Similar that we don't have a rating system for life gain, or creatures (Apart from the Value score, which is different. Maybe use that score instead?)

**Comment by ShawnieBoy** [comment]
Could possibly include the 'static' value as well. I'm mainly thinking about housekeeping and the scriptbuilder, but also the possibility that these values are either missing and causing unseen problems or included and not really doing anything.

**Comment by melvinzhang** [comment]
removal is used to give a boost to getCardScore, the formula is roughly:
  cardDefinition.getValue()*100
+ cardDefinition.getRemoval()*50
+cardDefinition.getRarity()*30
- cardDefinition.getConvertedCost()*20

My best guess is that it relates to the importance of removal in limited,
the format Magarena is designed for (40 cards, randomly generated).

If we look at getCardScore, we see it is used when cards are moved from
zone to zone. In particular, MagicRemoveCardAction's score is -
getCardScore which is the card disadvantage of playing the card. This
implies that a card with higher score tends to stay in the hand longer
since there is a high cost associated with removing it from hand.

One possible effect of removing the removal value is that removal spell
will be more freely played to remove low scoring permanents.

**Comment by ShawnieBoy** [comment]
I see now, thanks for that.

If there needs to be extra weight for the removal cards, would it not make sense to add these values to the abilities themselves instead of a score of 1-5 per card? Would help to standardise the values for the AI and also lift that from the scripter.

**Comment by melvinzhang** [comment]
Good idea. However, removal is an effect rather than an ability. Effects do not currently have an associated score.
