### ISSUE TITLE
Veilstone Amulet (New Card)

### ISSUE THREAD

**Issue by kelsioboy** [magarena/magarena#952]
name=Veilstone Amulet
image=http://magiccards.info/scans/en/fut/166.jpg
value=3.808
rarity=R
type=Artifact
cost={3}
ability=Whenever you cast a spell, creatures you control gains hexproof until end of turn.
timing=artifact
oracle=Whenever you cast a spell, creatures you control can't be the targets of spells or abilities your opponents control this turn.

**Comment by melvinzhang** [comment]
The ability given is not the same as hexproof. If the opponent gains control of your creature with the ability, the opponent cannot target the creature. With hexproof, when the opponent gains control, he/she can target the creature.

**Comment by kelsioboy** [comment]
I found it to be equal to " Privileged Position" because the card is written like.

**Comment by ShawnieBoy** [comment]
The difference is that the creatures don't gain the ability - [Arcane Lighthouse](http://magiccards.info/c14/en/59.html) shouldn't have any effect.

**Comment by melvinzhang** [comment]
Sorry, the issue I mentioned above is incorrect. If an opponent gains control of your creature, the creature (now belonging to the opponent) will no longer have the "can't be target", whereas in the submitted script it will continue to have hexproof. 

Another issue is that it should affect creatures that enter after the trigger resolves. See quote below for the reason.

"The effect of Veilstone Amulet's trigger doesn't change the characteristics of any objects, so the set of objects isn't locked in when the trigger resolves; so a creature that enters the battlefield after the trigger resolves (for instance, one that you cast which triggered the Amulet) can't be targeted by opponent's spells/abilities that turn either. Meanwhile, granting hexproof would change characteristics, so that would work differently." -- http://www.mtgsalvation.com/forums/magic-fundamentals/magic-rulings/magic-rulings-archives/613913-ruling-question-veilstone-amulet

**Comment by kelsioboy** [comment]
Thank you for the explanation  :+1:
